version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
#    volumes:
#      - ./data:/var/lib/postgresql/data

  server:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
#    volumes:
#      - .:/usr/src/server